export const maps = [
  {
    id: "neon",
    name: "Neon Meridian",
    tag: "Modern city",
    tint: 0x071024,
    fog: 0x11172b,
    accent: "#54dcff",
    sky: "#08112c",

    // Gameplay route. Keep this stable: Game, AI, traffic and checkpoints use it.
    route: [
      [-36, -276],
      [88, -258],
      [172, -212],
      [126, -148],
      [236, -104],
      [282, -18],
      [188, 34],
      [260, 126],
      [164, 214],
      [42, 182],
      [18, 96],
      [-86, 232],
      [-226, 178],
      [-282, 64],
      [-188, 8],
      [-266, -96],
      [-164, -214],
      [-62, -158],
      [-18, -72],
      [-122, -42],
      [-174, -142],
      [-96, -236],
    ],
    straightSegments: [0, 1, 8, 9, 17],
    shortcuts: [
      { from: 2, to: 6, side: -1, bend: 64, elevated: true, label: "SKY CUT" },
      { from: 10, to: 13, side: 1, bend: 72, elevated: false, label: "SERVICE CUT" },
      { from: 17, to: 20, side: -1, bend: 52, elevated: true, label: "FLYOVER" },
    ],

    // Environment grammar for Neon Meridian.
    environment: {
      version: 1,
      maxBuildingsDesktop: 76,
      maxBuildingsMobile: 52,
      routeOffset: 14,

      districts: [
        {
          from: 0,
          to: 1,
          type: "boulevard",
          name: "Meridian Boulevard",
          density: 0.86,
          families: [
            "mixedUse",
            "hotel",
            "commercial",
            "residential",
            "lowRiseStorefront",
            "officeSlab",
          ],
          heights: [18, 46],
          storefrontChance: 0.78,
          sideStreetChance: 0.55,
          propDensity: 0.86,
          roadDetail: 0.8,
        },
        {
          from: 2,
          to: 4,
          type: "downtown",
          name: "Central Core",
          density: 1,
          families: [
            "glassTower",
            "steppedTower",
            "hotel",
            "mixedUse",
            "officeSlab",
          ],
          heights: [42, 104],
          storefrontChance: 0.38,
          sideStreetChance: 0.74,
          propDensity: 0.62,
          roadDetail: 1,
        },
        {
          from: 5,
          to: 7,
          type: "transit",
          name: "Halo Interchange",
          density: 0.92,
          families: [
            "glassTower",
            "parking",
            "commercial",
            "mixedUse",
            "officeSlab",
          ],
          heights: [22, 74],
          storefrontChance: 0.48,
          sideStreetChance: 0.62,
          propDensity: 0.72,
          roadDetail: 0.9,
        },
        {
          from: 8,
          to: 10,
          type: "underpass",
          name: "Lower Meridian",
          density: 0.8,
          families: [
            "mixedUse",
            "residential",
            "parking",
            "commercial",
            "warehouse",
          ],
          heights: [14, 44],
          storefrontChance: 0.62,
          sideStreetChance: 0.35,
          propDensity: 0.9,
          roadDetail: 0.95,
        },
        {
          from: 11,
          to: 12,
          type: "neonDistrict",
          name: "Signal Row",
          density: 0.96,
          families: [
            "commercial",
            "glassTower",
            "hotel",
            "mixedUse",
            "lowRiseStorefront",
          ],
          heights: [24, 78],
          storefrontChance: 0.9,
          sideStreetChance: 0.72,
          propDensity: 0.95,
          roadDetail: 1,
        },
        {
          from: 13,
          to: 14,
          type: "bridge",
          name: "Meridian Crossing",
          density: 0.58,
          families: ["hotel", "glassTower", "parking", "commercial", "officeSlab"],
          heights: [18, 58],
          storefrontChance: 0.32,
          sideStreetChance: 0.2,
          propDensity: 0.46,
          roadDetail: 0.65,
        },
        {
          from: 15,
          to: 16,
          type: "skyline",
          name: "North Skyline",
          density: 0.7,
          families: [
            "glassTower",
            "steppedTower",
            "residential",
            "hotel",
            "officeSlab",
          ],
          heights: [30, 88],
          storefrontChance: 0.28,
          sideStreetChance: 0.25,
          propDensity: 0.5,
          roadDetail: 0.7,
        },
      ],

      landmarks: [
        {
          id: "meridianSpire",
          type: "spire",
          name: "Meridian Spire",
          segment: 2,
          side: 1,
          distance: 49,
          scale: 1.0,
        },
        {
          id: "glassArc",
          type: "arcTower",
          name: "Arc Meridian Tower",
          segment: 4,
          side: -1,
          distance: 43,
          scale: 0.92,
        },
        {
          id: "haloTransit",
          type: "transitHub",
          name: "Halo Transit Hub",
          segment: 6,
          side: 1,
          distance: 44,
          scale: 1.0,
        },
        {
          id: "signalPlaza",
          type: "neonPlaza",
          name: "Signal Plaza",
          segment: 11,
          side: -1,
          distance: 37,
          scale: 1.0,
        },
        {
          id: "grandInterchange",
          type: "interchange",
          name: "Grand Meridian Interchange",
          segment: 13,
          side: 1,
          distance: 45,
          scale: 1.0,
        },
        {
          id: "meridianHotel",
          type: "hotel",
          name: "Meridian Crown Hotel",
          segment: 15,
          side: -1,
          distance: 45,
          scale: 0.95,
        },
        {
          id: "digitalDistrict",
          type: "billboardDistrict",
          name: "Digital District",
          segment: 3,
          side: 1,
          distance: 31,
          scale: 0.86,
        },
      ],

      park: {
        x: -58,
        z: 48,
        radius: 24,
      },

      signage: [
        { text: "MERIDIAN AVE", segment: 0, side: -1, distance: 15.2 },
        { text: "NORTH DISTRICT", segment: 2, side: 1, distance: 16.0 },
        { text: "EAST TERMINAL", segment: 5, side: -1, distance: 15.4 },
        { text: "CITY LOOP", segment: 8, side: 1, distance: 15.3 },
        { text: "SIGNAL ROW", segment: 11, side: -1, distance: 15.3 },
        { text: "CENTRAL STATION", segment: 15, side: 1, distance: 15.6 },
      ],

      streetScenes: [
        {
          type: "taxiDropoff",
          segment: 1,
          side: -1,
          distance: 17.8,
          label: "CITYLINK",
        },
        {
          type: "construction",
          segment: 4,
          side: 1,
          distance: 18.4,
          label: "NORTH DISTRICT",
        },
        {
          type: "transitStop",
          segment: 6,
          side: 1,
          distance: 16.7,
          label: "HALO LINE",
        },
        {
          type: "delivery",
          segment: 9,
          side: -1,
          distance: 18.2,
          label: "SERVICE ACCESS",
        },
        {
          type: "parkingEntry",
          segment: 11,
          side: -1,
          distance: 16.8,
          label: "PARKING",
        },
        {
          type: "maintenance",
          segment: 14,
          side: 1,
          distance: 17.6,
          label: "DOCK 07",
        },
      ],
    },
  },

  {
    id: "coast",
    name: "Azure Run",
    tag: "Coastal highway",
    tint: 0x07313a,
    fog: 0x244957,
    accent: "#43f3d0",
    sky: "#74c4d7",
    route: [
      [-284, -82],
      [-222, -174],
      [-94, -218],
      [24, -174],
      [142, -214],
      [276, -116],
      [216, -18],
      [288, 92],
      [158, 202],
      [36, 146],
      [-86, 230],
      [-238, 146],
      [-166, 42],
      [-292, 12],
      [-234, -48],
      [-128, -28],
      [-64, -112],
      [-178, -132],
    ],
    straightSegments: [0, 1, 5, 8, 14],
    shortcuts: [
      { from: 1, to: 5, side: 1, bend: 86, elevated: true, label: "COAST BRIDGE" },
      { from: 9, to: 12, side: -1, bend: 66, elevated: false, label: "BEACH CUT" },
    ],
  },

  {
    id: "dock",
    name: "Ironpoint",
    tag: "Industrial dockyard",
    tint: 0x1f1920,
    fog: 0x362b32,
    accent: "#ffa255",
    sky: "#352d3d",
    route: [
      [-286, 42],
      [-238, -126],
      [-122, -216],
      [12, -154],
      [124, -226],
      [276, -112],
      [198, -12],
      [286, 82],
      [164, 226],
      [38, 176],
      [-54, 258],
      [-214, 182],
      [-132, 68],
      [-246, 18],
      [-184, -54],
      [-42, -52],
      [38, 42],
      [-72, 118],
    ],
    straightSegments: [0, 5, 8, 12, 15],
    shortcuts: [
      { from: 2, to: 5, side: -1, bend: 70, elevated: true, label: "GANTRY" },
      { from: 11, to: 15, side: 1, bend: 92, elevated: false, label: "CONTAINER CUT" },
    ],
  },

  {
    id: "mesa",
    name: "Sundown Pass",
    tag: "Desert mountain",
    tint: 0x3a2118,
    fog: 0xa35738,
    accent: "#ffd05a",
    sky: "#e7874d",
    route: [
      [-288, -96],
      [-206, -214],
      [-76, -142],
      [42, -260],
      [196, -188],
      [286, -46],
      [186, 46],
      [264, 162],
      [94, 246],
      [-8, 154],
      [-128, 236],
      [-286, 116],
      [-184, 18],
      [-254, -42],
      [-112, -62],
      [-28, 32],
      [-126, 112],
      [-232, 38],
    ],
    straightSegments: [0, 3, 4, 8, 13],
    shortcuts: [
      { from: 2, to: 5, side: 1, bend: 76, elevated: true, label: "CANYON JUMP" },
      { from: 8, to: 12, side: -1, bend: 96, elevated: false, label: "DRY WASH" },
    ],
  },
];

const carNames = [
  "Apex GT",
  "Vector R",
  "Monarch LX",
  "Vanta RS",
  "Kestrel Turbo",
  "Eclipse V8",
  "Cinder XR",
  "Solace 720",
  "Riot Coupe",
  "Nova Sprint",
];

const bikeNames = [
  "Volt Arrow",
  "Rogue 900",
  "Kite RR",
  "Phantom 8",
  "Viper Neo",
  "Eon Tracker",
  "Strix 1000",
  "Luma R",
  "Sable 650",
  "Orion X",
];

const heavyNames = ["Bastion Interceptor", "Titan Hauler", "Wardog 4x4"];
const monsterNames = ["Gravel King", "Mammoth R", "Crusher X"];

const palettes = [
  "#ff4b63",
  "#2de2e6",
  "#ffc857",
  "#9b7bff",
  "#f5f7ff",
  "#79e68c",
];

const carProfiles = [
  "coupe",
  "super",
  "muscle",
  "hyper",
  "rally",
  "coupe",
  "muscle",
  "super",
  "rally",
  "hyper",
];

const bikeProfiles = [
  "sport",
  "naked",
  "cruiser",
  "dirt",
  "sport",
  "naked",
  "sport",
  "cruiser",
  "dirt",
  "sport",
];

const carTypes = {
  coupe: "sports coupe",
  muscle: "muscle / GT",
  super: "supercar",
  hyper: "hypercar",
  rally: "rally / offroad",
};

const bikeTypes = {
  sport: "sports bike",
  naked: "street bike",
  cruiser: "cruiser",
  dirt: "offroad bike",
};

export const vehicles = [
  ...carNames.map((name, i) => ({
    id: `car${i}`,
    name,
    type: carTypes[carProfiles[i]],
    profile: carProfiles[i],
    kind: "car",
    top: 77 + (i % 4) * 4,
    accel: 63 + ((i * 7) % 25),
    handling: 57 + ((i * 11) % 30),
    braking: 65 + ((i * 5) % 24),
    armor: 39 + ((i * 9) % 31),
    boost: 64 + ((i * 6) % 27),
    color: palettes[i % palettes.length],
  })),

  ...bikeNames.map((name, i) => ({
    id: `bike${i}`,
    name,
    type: bikeTypes[bikeProfiles[i]],
    profile: bikeProfiles[i],
    kind: "bike",
    top: 85 + (i % 4) * 4,
    accel: 76 + ((i * 5) % 20),
    handling: 78 + ((i * 7) % 19),
    braking: 72 + ((i * 3) % 21),
    armor: 21 + ((i * 4) % 20),
    boost: 73 + ((i * 6) % 22),
    color: palettes[(i + 2) % palettes.length],
  })),

  ...heavyNames.map((name, i) => ({
    id: `heavy${i}`,
    name,
    type: "armored weapon platform",
    profile: "interceptor",
    kind: "heavy",
    top: 47 + i * 3,
    accel: 39 + i * 4,
    handling: 31 + i * 5,
    braking: 57 + i * 4,
    armor: 94 - i * 5,
    boost: 36 + i * 5,
    armed: true,
    offroadImmune: true,
    color: ["#273449", "#45565a", "#403a35"][i],
  })),

  ...monsterNames.map((name, i) => ({
    id: `monster${i}`,
    name,
    type: "monster truck",
    profile: "monster",
    kind: "monster",
    top: 46 + i * 3,
    accel: 42 + i * 5,
    handling: 28 + i * 4,
    braking: 48 + i * 5,
    armor: 88 + i * 3,
    boost: 34 + i * 4,
    canSmash: true,
    color: ["#7bdc6b", "#d95545", "#5b70ff"][i],
  })),
];

export const modes = [
  {
    id: "race",
    title: "Race",
    detail: "Three laps. Own the route.",
  },
  {
    id: "time",
    title: "Time Trial",
    detail: "Beat your personal best.",
  },
  {
    id: "escape",
    title: "Police Escape",
    detail: "Outrun the heat. Reach extraction.",
  },
  {
    id: "versus",
    title: "Police vs Thief",
    detail: "LAN lobby role pursuit.",
  },
  {
    id: "friend",
    title: "Friend Chase",
    detail: "Catch or escape before time runs out.",
  },
];
