export const maps = [
  {
    id: "neon",
    name: "Neon Meridian",
    tag: "Modern city",
    tint: 0x071024,
    fog: 0x11172b,
    accent: "#54dcff",
    sky: "#08112c",

    // Gameplay route. Keep this stable: Game, AI, traffic and checkpoints use it.
    route: [
      [0, -86],
      [52, -84],
      [88, -70],
      [112, -40],
      [122, -6],
      [106, 18],
      [116, 46],
      [96, 74],
      [58, 91],
      [16, 94],
      [-25, 84],
      [-62, 68],
      [-96, 42],
      [-114, 9],
      [-107, -24],
      [-82, -53],
      [-43, -73],
    ],

    // Environment grammar for Neon Meridian.
    environment: {
      version: 1,
      maxBuildingsDesktop: 68,
      maxBuildingsMobile: 48,
      routeOffset: 14,

      districts: [
        {
          from: 0,
          to: 1,
          type: "boulevard",
          name: "Meridian Boulevard",
          density: 0.86,
          families: ["mixedUse", "hotel", "commercial", "residential"],
          heights: [18, 46],
          storefrontChance: 0.78,
          sideStreetChance: 0.55,
        },
        {
          from: 2,
          to: 4,
          type: "downtown",
          name: "Central Core",
          density: 1,
          families: ["glassTower", "steppedTower", "hotel", "mixedUse"],
          heights: [42, 104],
          storefrontChance: 0.38,
          sideStreetChance: 0.74,
        },
        {
          from: 5,
          to: 7,
          type: "transit",
          name: "Halo Interchange",
          density: 0.92,
          families: ["glassTower", "parking", "commercial", "mixedUse"],
          heights: [22, 74],
          storefrontChance: 0.48,
          sideStreetChance: 0.62,
        },
        {
          from: 8,
          to: 10,
          type: "underpass",
          name: "Lower Meridian",
          density: 0.8,
          families: ["mixedUse", "residential", "parking", "commercial"],
          heights: [14, 44],
          storefrontChance: 0.62,
          sideStreetChance: 0.35,
        },
        {
          from: 11,
          to: 12,
          type: "neonDistrict",
          name: "Signal Row",
          density: 0.96,
          families: ["commercial", "glassTower", "hotel", "mixedUse"],
          heights: [24, 78],
          storefrontChance: 0.9,
          sideStreetChance: 0.72,
        },
        {
          from: 13,
          to: 14,
          type: "bridge",
          name: "Meridian Crossing",
          density: 0.58,
          families: ["hotel", "glassTower", "parking", "commercial"],
          heights: [18, 58],
          storefrontChance: 0.32,
          sideStreetChance: 0.2,
        },
        {
          from: 15,
          to: 16,
          type: "skyline",
          name: "North Skyline",
          density: 0.7,
          families: ["glassTower", "steppedTower", "residential", "hotel"],
          heights: [30, 88],
          storefrontChance: 0.28,
          sideStreetChance: 0.25,
        },
      ],

      landmarks: [
        {
          id: "meridianSpire",
          type: "spire",
          name: "Meridian Spire",
          segment: 2,
          side: 1,
          distance: 49,
          scale: 1.0,
        },
        {
          id: "glassArc",
          type: "arcTower",
          name: "Arc Meridian Tower",
          segment: 4,
          side: -1,
          distance: 43,
          scale: 0.92,
        },
        {
          id: "haloTransit",
          type: "transitHub",
          name: "Halo Transit Hub",
          segment: 6,
          side: 1,
          distance: 44,
          scale: 1.0,
        },
        {
          id: "signalPlaza",
          type: "neonPlaza",
          name: "Signal Plaza",
          segment: 11,
          side: -1,
          distance: 37,
          scale: 1.0,
        },
        {
          id: "grandInterchange",
          type: "interchange",
          name: "Grand Meridian Interchange",
          segment: 13,
          side: 1,
          distance: 45,
          scale: 1.0,
        },
        {
          id: "meridianHotel",
          type: "hotel",
          name: "Meridian Crown Hotel",
          segment: 15,
          side: -1,
          distance: 45,
          scale: 0.95,
        },
        {
          id: "digitalDistrict",
          type: "billboardDistrict",
          name: "Digital District",
          segment: 3,
          side: 1,
          distance: 31,
          scale: 0.86,
        },
      ],

      park: {
        x: -58,
        z: 48,
        radius: 24,
      },

      signage: [
        { text: "MERIDIAN AVE", segment: 0, side: -1, distance: 15.2 },
        { text: "NORTH DISTRICT", segment: 2, side: 1, distance: 16.0 },
        { text: "EAST TERMINAL", segment: 5, side: -1, distance: 15.4 },
        { text: "CITY LOOP", segment: 8, side: 1, distance: 15.3 },
        { text: "SIGNAL ROW", segment: 11, side: -1, distance: 15.3 },
        { text: "CENTRAL STATION", segment: 15, side: 1, distance: 15.6 },
      ],
    },
  },

  {
    id: "coast",
    name: "Azure Run",
    tag: "Coastal highway",
    tint: 0x07313a,
    fog: 0x244957,
    accent: "#43f3d0",
    sky: "#74c4d7",
    route: [
      [-104, -40],
      [-42, -77],
      [42, -70],
      [104, -25],
      [114, 38],
      [45, 79],
      [-55, 69],
      [-114, 35],
    ],
  },

  {
    id: "dock",
    name: "Ironpoint",
    tag: "Industrial dockyard",
    tint: 0x1f1920,
    fog: 0x362b32,
    accent: "#ffa255",
    sky: "#352d3d",
    route: [
      [-105, 20],
      [-78, -62],
      [-17, -82],
      [67, -70],
      [112, -15],
      [90, 82],
      [12, 96],
      [-66, 79],
    ],
  },

  {
    id: "mesa",
    name: "Sundown Pass",
    tag: "Desert mountain",
    tint: 0x3a2118,
    fog: 0xa35738,
    accent: "#ffd05a",
    sky: "#e7874d",
    route: [
      [-105, -35],
      [-72, -83],
      [-8, -67],
      [54, -102],
      [110, -42],
      [83, 35],
      [25, 83],
      [-53, 85],
      [-109, 47],
    ],
  },
];

const carNames = [
  "Apex GT",
  "Vector R",
  "Monarch LX",
  "Vanta RS",
  "Kestrel Turbo",
  "Eclipse V8",
  "Cinder XR",
  "Solace 720",
  "Riot Coupe",
  "Nova Sprint",
];

const bikeNames = [
  "Volt Arrow",
  "Rogue 900",
  "Kite RR",
  "Phantom 8",
  "Viper Neo",
  "Eon Tracker",
  "Strix 1000",
  "Luma R",
  "Sable 650",
  "Orion X",
];

const heavyNames = ["Bastion Interceptor", "Titan Hauler", "Wardog 4x4"];

const palettes = [
  "#ff4b63",
  "#2de2e6",
  "#ffc857",
  "#9b7bff",
  "#f5f7ff",
  "#79e68c",
];

const carProfiles = [
  "coupe",
  "super",
  "muscle",
  "hyper",
  "rally",
  "coupe",
  "muscle",
  "super",
  "rally",
  "hyper",
];

const bikeProfiles = [
  "sport",
  "naked",
  "cruiser",
  "dirt",
  "sport",
  "naked",
  "sport",
  "cruiser",
  "dirt",
  "sport",
];

const carTypes = {
  coupe: "sports coupe",
  muscle: "muscle / GT",
  super: "supercar",
  hyper: "hypercar",
  rally: "rally / offroad",
};

const bikeTypes = {
  sport: "sports bike",
  naked: "street bike",
  cruiser: "cruiser",
  dirt: "offroad bike",
};

export const vehicles = [
  ...carNames.map((name, i) => ({
    id: `car${i}`,
    name,
    type: carTypes[carProfiles[i]],
    profile: carProfiles[i],
    kind: "car",
    top: 77 + (i % 4) * 4,
    accel: 63 + ((i * 7) % 25),
    handling: 57 + ((i * 11) % 30),
    braking: 65 + ((i * 5) % 24),
    armor: 39 + ((i * 9) % 31),
    boost: 64 + ((i * 6) % 27),
    color: palettes[i % palettes.length],
  })),

  ...bikeNames.map((name, i) => ({
    id: `bike${i}`,
    name,
    type: bikeTypes[bikeProfiles[i]],
    profile: bikeProfiles[i],
    kind: "bike",
    top: 85 + (i % 4) * 4,
    accel: 76 + ((i * 5) % 20),
    handling: 78 + ((i * 7) % 19),
    braking: 72 + ((i * 3) % 21),
    armor: 21 + ((i * 4) % 20),
    boost: 73 + ((i * 6) % 22),
    color: palettes[(i + 2) % palettes.length],
  })),

  ...heavyNames.map((name, i) => ({
    id: `heavy${i}`,
    name,
    type: "armored interceptor",
    profile: "interceptor",
    kind: "heavy",
    top: 51 + i * 3,
    accel: 43 + i * 4,
    handling: 35 + i * 5,
    braking: 57 + i * 4,
    armor: 94 - i * 5,
    boost: 43 + i * 5,
    color: ["#273449", "#45565a", "#403a35"][i],
  })),
];

export const modes = [
  {
    id: "race",
    title: "Race",
    detail: "Three laps. Own the route.",
  },
  {
    id: "time",
    title: "Time Trial",
    detail: "Beat your personal best.",
  },
  {
    id: "escape",
    title: "Police Escape",
    detail: "Outrun the heat. Reach extraction.",
  },
  {
    id: "versus",
    title: "Police vs Thief",
    detail: "LAN lobby role pursuit.",
  },
  {
    id: "friend",
    title: "Friend Chase",
    detail: "Catch or escape before time runs out.",
  },
];
